### ISSUE TITLE
配置文件解析 · GitBook

### ISSUE THREAD

**Issue by icowan** [icowan/cloud-website#62]
https://docs.nsini.com/start/config.html

**Comment by springfred** [comment]
网站域名“https://kplcloud.nsini.com”和“http://kplcloud.kpaas.nsini.com”是什么关系？

**Comment by icowan** [comment]
@springfred  一样，都可以访问，我只是将 kplcloud.nsini.com 通过ha转发到了 kplcloud.kpaasn.nsini.com 而已
