### ISSUE TITLE
安装kplcloud · 开普勒云平台使用教程

### ISSUE THREAD

**Issue by icowan** [icowan/cloud-website#83]
https://docs.nsini.com/install/kpaas.html

**Comment by springfred** [comment]
使用github授权登录未成功， 请问是什么问题
Github设定
    Homepage URL：
    https://kplcloud.abc123.com

    Authorization callback URL：
    https://kplcloud.abc123.com

浏览器输入
http://kplcloud.kpaas.abc123.com

github授权之后， 浏览器跳转到
https://kplcloud.abc123.com


出现了：default backend - 404

**Comment by icowan** [comment]
@springfred  浏览器也要输入这个地址  https://kplcloud.abc123.com

**Comment by springfred** [comment]
> https://kplcloud.abc123.com
浏览器直接输入，也是出现default backend - 404

**Comment by springfred** [comment]
install/kubernetes/gateway.yaml
install/kubernetes/kpaas/virtualservice.yaml
这两个文件执行有错
`
[root@rancherserver kplcloud]# kubectl -n kpaas create -f install/kubernetes/kpaas/virtualservice.yaml
error: unable to recognize "install/kubernetes/kpaas/virtualservice.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
[root@rancherserver kplcloud]# kubectl -n kpaas create -f install/kubernetes/gateway.yaml
error: unable to recognize "install/kubernetes/gateway.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

`
